#define SEC_LEVEL_GREEN 0
#define SEC_LEVEL_BLUE 1
#define SEC_LEVEL_VIOLET 2
#define SEC_LEVEL_ORANGE 3
#define SEC_LEVEL_AMBER 4
// OCULIS EDIT ADDITION START - ALERTS
#define SEC_LEVEL_WHITE 5
#define SEC_LEVEL_CRIMSON 6
#define SEC_LEVEL_RED 7
#define SEC_LEVEL_BLACK 8 // you gonna die
#define SEC_LEVEL_DELTA 9
#define SEC_LEVEL_EPSILON 10 // CENTCOM IS ANGY!!!
#define SEC_LEVEL_GAMMA 11 // Oh shit bois
#define SEC_LEVEL_FEDERAL 12 // THE FUCKING FEDS ARE HERE!!!
// OCULIS EDIT ADDITION END
